### ISSUE TITLE
Mention how to build a release to minimize application size

### ISSUE THREAD

**Issue by gangefors** [airdcpp-web/airdcpp-web.github.io#1]
There is no mention in the documentation on how to build a proper release. The default building instruction builds a release with debug symbols and the libs for the app takes up almost 200MB.

When building with `cmake -DCMAKE_BUILD_TYPE=Release .` the application size is greatly reduced. For the ones that want to have a system that takes up less space this information is very helpful.

**Comment by maksis** [comment]
Yeah, that's definitely helpful if you are low on disk space. I wouldn't recommend the option to be used otherwise since the symbols are useful when experiencing crashes/deadlocks (there have still been those quite recently).

**Comment by gangefors** [comment]
For building a minimal docker image and running the software on limited systems, like RaspberryPi and similar boards, space is important. But I'm with you regarding the symbols being needed if one wants to debug any crashes. But for users that don't want to do that, a couple of rows in the build section regarding this would be helpful.

**Comment by maksis** [comment]
@gangefors is your docker image something that could be mentioned in the documentation?

**Comment by gangefors** [comment]
If you want you can mention it and link to https://hub.docker.com/r/gangefors/airdcpp-webclient/

I've been using it since 1.1.0 and it has worked really good. I'm trying to rebuild it every time a new version comes out. But if you want to use my Dockerfile and create an official image in your own repo I'm fine with that. If you have it in your repo you can set it up to build through Docker hub every time you make a release.

If you have any questions just send me a message (mail available in the Dockerfile).

**Comment by maksis** [comment]
Your image is now mentioned at https://airdcpp-web.github.io/docs/installation/installation.html

I prefer keeping away from packaging so I'm happy with the current setup.

**Comment by maksis** [comment]
https://airdcpp-web.github.io/docs/advanced/compiling-options.html
