### ISSUE TITLE
Add an explicative screenshot

### ISSUE THREAD

**Issue by Kcchouette** [airdcpp-web/airdcpp-web.github.io#2]
It would be great to add a screenshot, and explain the general interface of airdcpp-web.

eg:

- an arrow to message: "here the interface where you can send private message to other user"
- an arrow to hash speed and network download speed: "here you can see at which speed you hash is done, and your upload/download is too"
- etc

**Comment by Kcchouette** [comment]
@maksis any news about this enhancement of the doc?

**Comment by maksis** [comment]
Sorry, not yet! I'll try to get something done with it soon.
